version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:admin@postgres:5432/school_management'
      JWT_SECRET: 'your-super-secret-jwt-key'
      JWT_REFRESH_SECRET: 'your-super-secret-refresh-key'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
